version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: endpoint do RDS
      WORDPRESS_DB_USER: nome do usuário principal do banco de dados
      WORDPRESS_DB_PASSWORD: senha do usuário principal do banco de dados
      WORDPRESS_DB_NAME: nome do banco de dados
      WORDPRESS_TABLE_CONFIG: wp_
