version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: db-project-docker.calezovcy8cf.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: user_database
      WORDPRESS_DB_PASSWORD: elementar
      WORDPRESS_DB_NAME: database_mysql
      WORDPRESS_TABLE_CONFIG: wp_
